### ISSUE TITLE
error when importing the bayesflow

### ISSUE THREAD

**Issue by Shuwan-Wang** [stefanradev93/BayesFlow#104]
Hi Stefan et al.,

I am so impressed by the bayesflow work. However, when I try to implement it myself, I got an error when importing the bayesflow.

I have tried with Pycharm/Anaconda, they gave me the same error message:

ValueError: Arg specs do not match: original=FullArgSpec(args=['input', 'dtype', 'name', 'layout'], varargs=None, varkw=None, defaults=(None, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), new=FullArgSpec(args=['input', 'dtype', 'name'], varargs=None, varkw=None, defaults=(None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), fn=<function ones_like_v2 at 0x000002D9E1F41A80>

Do you know what happened and how to solve this?

Thank you so much!
Best regards,
Shuwan

**Comment by stefanradev93** [comment]
Hi Shuwan, I have never seen such an error before. What system are you using (e.g., Python version, TensorFlow version, etc) and did you install bayesflow via pip?
--Stefan

**Comment by Shuwan-Wang** [comment]
Hi, 

I am using the latest Python (3.11.5) and I never installed TensorFlow before installing Bayesflow. Yes, I installed the bayesflow via pip in the terminal.

Thanks!
Shuwan

**Comment by stefanradev93** [comment]
It should have automatically been installed as part of the dependencies. Can you try with Python 3.10 following these instructions:

https://github.com/stefanradev93/BayesFlow/blob/master/INSTALL.rst

? 

Also, do you have Windows or Linux/Mac?

**Comment by Shuwan-Wang** [comment]
Yes, I can reinstall Python 3.10, and I have Windows.

**Comment by stefanradev93** [comment]
Let me know how this goes.

**Comment by Shuwan-Wang** [comment]
Hi,

I installed bayesflow via pip in Python 3.10.1, and it really seems downloaded all the packages and dependencies.

However, when I import bayesflow at the editor, it generates the following error:

C:\Users\swtyb\PycharmProjects\pythonProject4\venv\Scripts\python.exe C:\Users\swtyb\PycharmProjects\pythonProject\draft\example.py 
Traceback (most recent call last):
  File "C:\Users\swtyb\PycharmProjects\pythonProject\draft\example.py", line 2, in <module>
    import bayesflow as bf
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\bayesflow\__init__.py", line 25, in <module>
    from bayesflow import amortizers, default_settings, diagnostics, losses, networks, trainers, sensitivity
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\bayesflow\amortizers.py", line 30, in <module>
    import tensorflow_probability as tfp
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\substrates\__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 40, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\swtyb\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\experimental\__init__.py", line 31, in <module>
    from tensorflow_probability.python.experimental import bayesopt
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\experimental\bayesopt\__init__.py", line 17, in <module>
    from tensorflow_probability.python.experimental.bayesopt import acquisition
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\experimental\bayesopt\acquisition\__init__.py", line 17, in <module>
    from tensorflow_probability.python.experimental.bayesopt.acquisition.acquisition_function import AcquisitionFunction
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\experimental\bayesopt\acquisition\acquisition_function.py", line 22, in <module>
    from tensorflow_probability.python.internal import prefer_static as ps
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\internal\prefer_static.py", line 361, in <module>
    ones_like = _copy_docstring(tf.ones_like, _ones_like)
  File "C:\Users\swtyb\PycharmProjects\pythonProject4\venv\lib\site-packages\tensorflow_probability\python\internal\prefer_static.py", line 84, in _copy_docstring
    raise ValueError(
ValueError: Arg specs do not match: original=FullArgSpec(args=['input', 'dtype', 'name', 'layout'], varargs=None, varkw=None, defaults=(None, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), new=FullArgSpec(args=['input', 'dtype', 'name'], varargs=None, varkw=None, defaults=(None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), fn=<function ones_like_v2 at 0x000002571FA51CF0>

Process finished with exit code 1

I really don't know what happened here, could you take a look?

Thank you so much!
Best,
Shuwan
