### ISSUE TITLE
InvertibleNetwork error (Input 0 of layer "dense" is incompatible with the layer)

### ISSUE THREAD

**Issue by lucasgautheron** [stefanradev93/BayesFlow#183]
Hi,

InvertibleNetwork does not seem to be working for me  regardless of the input parameters (for instance, I cannot reproduce any of the [examples](https://bayesflow.org/examples.html) because of this issue.)

Here is a minimal example exhibiting the issue:

```python
import bayesflow.networks
bayesflow.networks.InvertibleNetwork(num_params=4)
```

Here is the error I get with this example:

```python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:11:10) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bayesflow.networks
2024-08-06 10:29:28.404900: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Failed to import TF-Keras. Please note that TF-Keras is not installed by default when you install TensorFlow Probability. This is so that JAX-only users do not have to install TensorFlow or TF-Keras. To use TensorFlow Probability with TensorFlow, please install the tf-keras or tf-keras-nightly package.
This can be be done through installing the tensorflow-probability[tf] extra.


WARNING:root:Some dependencies failed to load. BayesFlow modules may not work properly!
WARNING:root:No module named 'tf_keras'
>>> bayesflow.networks.InvertibleNetwork(num_params=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/bayesflow/inference_networks.py", line 139, in __init__
    self.coupling_layers = self._create_coupling_layers(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/bayesflow/inference_networks.py", line 257, in _create_coupling_layers
    CouplingLayer(coupling_design=design, coupling_settings=_coupling_settings, **settings)
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/bayesflow/coupling_networks.py", line 563, in __init__
    self.net1 = coupling_type(self.dim_out1, coupling_settings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/bayesflow/coupling_networks.py", line 83, in __init__
    self.scale = DenseCouplingNet(s_settings, dim_out)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/bayesflow/helper_networks.py", line 93, in __init__
    self.fc.build(input_shape=())
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/keras/src/layers/layer.py", line 225, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/keras/src/models/sequential.py", line 183, in build
    x = layer(x)
        ^^^^^^^^
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/envs/stan/lib/python3.12/site-packages/keras/src/layers/input_spec.py", line 202, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=0. Full shape received: ()
```

I installed the version 1.1.4. of the package as recommended (pip install bayesflow). It automatically installed tensorflow==2.16.2

Thank you for your help!

**Comment by LarsKue** [comment]
Hi @lucasgautheron, sorry for the late reply. I cannot reproduce the issue in a fresh environment. Did you follow the install instructions correctly? What version of Python are you using?

It also looks like the warnings in your output are hinting at another (possibly unrelated) issue:
> Failed to import TF-Keras.
> Some dependencies failed to load.
> No module named 'tf_keras'

Does running `pip install tf-keras=2.16` fix the issue? If not, can you please set up a fresh environment using

```
conda create bf-test python=3.11
conda activate bf-test
```

and then install the following dependency versions:

```
pip install bayesflow==1.1.6 tensorflow==2.15.1 tensorflow-probability==0.23.0
```
